"""Google API ports only. Concrete integrations begin in later phases."""

from typing import Any, Protocol, runtime_checkable

from src.google.models import DriveAccessResult, DriveConnectionResult, DriveFile


@runtime_checkable
class ReadOnlyDriveService(Protocol):
    def list_files(self, folder_id: str) -> tuple[DriveFile, ...]: ...
    def list_child_folders(self, folder_id: str) -> tuple[DriveFile, ...]: ...
    def get_file_metadata(self, file_id: str) -> DriveFile: ...
    def get_folder_metadata(self, folder_id: str) -> DriveFile: ...
    def find_files(
        self, folder_id: str, *, name_contains: str | None = None
    ) -> tuple[DriveFile, ...]: ...
    def file_exists(self, file_id: str) -> bool: ...
    def download_file(self, file_id: str) -> bytes: ...
    def export_file(self, file_id: str, mime_type: str) -> bytes: ...
    def update_file_content(
        self, file_id: str, content: bytes, mime_type: str
    ) -> DriveFile: ...
    def ensure_folder(self, parent_id: str, name: str) -> DriveFile: ...
    def create_file(
        self, folder_id: str, name: str, content: bytes, mime_type: str
    ) -> DriveFile: ...
    def test_connection(self, root_folder_id: str) -> DriveConnectionResult: ...
    def check_access(
        self, object_id: str | None, *, location: str, folder: bool, require_write: bool
    ) -> DriveAccessResult: ...


DriveService = ReadOnlyDriveService


class SheetsService(Protocol):
    def create_restaurant_ledger(self, folder_id: str, title: str) -> str: ...
    def read_range(self, spreadsheet_id: str, range_name: str) -> list[list[Any]]: ...
    def append_rows(
        self, spreadsheet_id: str, range_name: str, rows: list[list[Any]]
    ) -> None: ...


class GmailService(Protocol):
    def create_draft(
        self, recipient: str, subject: str, body: str, attachments: list[bytes]
    ) -> str: ...
    def send_message(
        self, recipient: str, subject: str, body: str, attachments: list[bytes]
    ) -> str: ...
    def get_message_metadata(self, provider_message_id: str) -> dict[str, str]: ...
